stages:
  - deploy

pages:
  stage: deploy
  image: rocker/r-ver:4.2
  before_script:
    - apt-get update && apt-get install wget curl gnupg openjdk-8-jdk -y 

  script: 
  - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - apt-get install ./google-chrome-stable_current_amd64.deb

  - Rscript jobstreet-web-scraping.R 