stages:
  - deploy

pages:
  stage: deploy
  image: rocker/r-ver:4.2
  before_script:
    - apt-get update && apt-get install wget curl gnupg openjdk-8-jdk -y 

  script:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

# Install Chrome
  - apt-get update && apt-get install -y google-chrome-stable 
      
# Install ChromeDriver
  - export $CHROMEDRIVER_DIR=/chromedriver
  - mkdir $CHROMEDRIVER_DIR
  - CHROME_VERSION=$(google-chrome --product-version | sed -ne 's/[^0-9]*\(\([0-9]\.\)\{0,4\}[0-9][^.]\).*/\1/p'); \
    CHROMEDRIVER_VERSION=$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION); \
    wget -q --continue -P $CHROMEDRIVER_DIR "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
  - unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR
  - export PATH="$CHROMEDRIVER_DIR:$PATH" 
  - Rscript jobstreet-web-scraping.R 


