stages:
  - deploy

pages:
  stage: deploy
  image: rocker/r-ver:4.2
  before_script:
    - apt-get update && apt-get install wget curl gnupg openjdk-8-jdk -y 

  script:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

# Install Chrome
  - apt-get update && apt-get install -y google-chrome-stable 
      
  - Rscript jobstreet-web-scraping.R 


