stages:
  - deploy

pages:
  stage: deploy
  image: rocker/r-ver:4.2
  before_script:
    - apt-get update && apt-get install wget curl gnupg openjdk-8-jdk -y 

  script: 
  - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - apt-get install ./google-chrome-stable_current_amd64.deb -y
  - chromeVersion=$(google-chrome --product-version) && chromeMajorVersion=${chromeVersion%%.*} && latestDriverReleaseURL=https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$chromeMajorVersion && wget $latestDriverReleaseURL && latestDriverVersionFileName="LATEST_RELEASE_"$chromeMajorVersion && latestFullDriverVersion=$(cat $latestDriverVersionFileName) && rm $latestDriverVersionFileName && finalURL="http://chromedriver.storage.googleapis.com/"$latestFullDriverVersion"/chromedriver_linux64.zip" && wget $finalURL && unzip chromedriver_linux64.zip && rm chromedriver_linux64.zip  

  - Rscript jobstreet-web-scraping.R 